### ISSUE TITLE
Bug when variant value has `as <type>`

### ISSUE THREAD

**Issue by faern** [JeffBelgum/derive-try-from-primitive#1]
Really handy crate :ok_hand: 

But I have found that if used on an enum like this:
```rust
#[derive(TryFromPrimitive)]
#[repr(u8)]
pub enum Bar {
    A = 10,
    B = 20 as u8,
}
```
it produces the following code:
```rust
impl Bar {
    pub fn try_from(n: u8) -> Option<Bar> {
        match n {
            10u8 => Some(Bar::A),
            10u8 => Some(Bar::B),
            _ => None,
        }
    }
}

```
Which is clearly wrong, because now `Bar::try_from(20)` will return `None` instead of `Some(Bar::B)`.

**Comment by JeffBelgum** [comment]
I'm finally getting around to addressing old issues. If it's still relevant to you, please reopen and let me know what use-case requires an explicit `as <type>`? I'm happy to add the functionality if it address a need.
